### ISSUE TITLE
Please update theme repo. 

### ISSUE THREAD

**Issue by tecfu** [gothinkster/realworld-starter-kit#25]
The SCSS files at https://github.com/gothinkster/conduit-bootstrap-template do not result in the compiled stylesheet found at https://demo.productionready.io/main.css. 

Please update.

**Comment by geromegrignon** [comment]
As part of a new version of the specs we are working on, we plan to update the theme.
You can track it and participate to the discussion here: https://github.com/gothinkster/realworld/issues/662
