### ISSUE TITLE
How to register my plans in WIP section(s)

### ISSUE THREAD

**Issue by adriatic** [gothinkster/realworld-starter-kit#59]
I would guess that the proper way would be to add an issue in the `https://github.com/gothinkster/realworld/tree/master/spec` repository (per item 4 in the [Ready to implement Conduit in a new framework?](https://github.com/gothinkster/realworld/tree/master/spec#ready-to-implement-conduit-in-a-new-framework)) and add my work to list of [issues](https://github.com/gothinkster/realworld/issues?q=is%3Aopen+is%3Aissue+label%3Awip)

My brief chat session in the [Gitter room](https://gitter.im/realworld-dev/main) led me to believe how people only post questions and nobody answers them

**Comment by geromegrignon** [comment]
Hello @adriatic, you can create a discussion about your wip here: https://github.com/gothinkster/realworld/discussions/new
Once complete, you can submit the implementation on [CodebaseShow](https://codebase.show/projects/realworld)
